# Generated by Django 3.0 on 2021-01-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210129_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, verbose_name='Максимальный объём встраиваемой памяти'),
        ),
    ]
